# Example config file

label: "CategoricalDQN"
env_name: "Seaquest-v0"
env_class: atari
estimator: &estimator atari
hidden_size: &hidden_size 512
seed: 23
cuda: &cuda yes
profiling: no
report_freq: &report_freq 10 # episodes

training:
  step_no: &step_no 40000000 # 2512000
  batch_size: &batch_size 32
  update_freq: &update_freq 4
  target_update_freq: &target_update_freq 24
  lr: &lr .000235
  gamma: &gamma 0.99

agent:
  name: "categorical"
  report_freq: *report_freq
  rescale: 84
  epsilon: 1
  epsilon_steps: 1000000
  experience_replay: 1000000
  cuda: *cuda
  estimator: *estimator
  update_freq: *update_freq
  target_update_freq: *target_update_freq
  batch_size: *batch_size
  lr: *lr
  gamma: *gamma
  hist_len: 1
  hidden_size: *hidden_size
  # Specific to CategoricalDQN
  atoms_no: 51
  v_min: -10
  v_max: 10

evaluator:
  eval_steps: 2400
  eval_eps: 1000
  eval_interval: 100000
  eval_start: 100000
  estimator: *estimator
  cuda: *cuda
