# Example config file

label: "CategoricalDQN"
env_class: catch
env_name: "Catcher-Level0-v0"
estimator: &estimator catch
hidden_size: &hidden_size 128
seed: 23
cuda: &cuda true
profiling: no
report_freq: &report_freq 500

training:
  step_no: &step_no 1200000 # 2512000
  batch_size: &batch_size 96
  update_freq: &update_freq 4
  target_update_freq: &target_update_freq 24
  lr: &lr .000635
  gamma: &gamma 0.99

agent:
  name: "dqn"
  report_freq: *report_freq
  rescale: no # where required
  epsilon: 1
  epsilon_steps: 100000
  experience_replay: 100000
  cuda: *cuda
  estimator: *estimator
  update_freq: *update_freq
  target_update_freq: *target_update_freq
  batch_size: *batch_size
  lr: *lr
  gamma: *gamma
  hist_len: 1
  hidden_size: *hidden_size

evaluator:
  eval_steps: 2400
  eval_eps: 1000
  eval_interval: 100000
  eval_start: 100000
  estimator: *estimator
  cuda: *cuda
